-- CreateTable
CREATE TABLE `Report` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fecha` DATETIME(3) NOT NULL,
    `correo` VARCHAR(191) NOT NULL,
    `distrito` VARCHAR(191) NOT NULL,
    `erocion_local` VARCHAR(191) NOT NULL,
    `latitud` INTEGER NOT NULL,
    `veg_dominante` VARCHAR(191) NOT NULL,
    `apellido` VARCHAR(191) NOT NULL,
    `presencia_presa` VARCHAR(191) NOT NULL,
    `temperatura` VARCHAR(191) NOT NULL,
    `descarga_electrica` VARCHAR(191) NOT NULL,
    `presencia_vado` VARCHAR(191) NOT NULL,
    `resultado_bmwp` VARCHAR(191) NOT NULL,
    `edad` INTEGER NOT NULL,
    `actividad_agricola` VARCHAR(191) NOT NULL,
    `provincia` VARCHAR(191) NOT NULL,
    `presencia_puente` VARCHAR(191) NOT NULL,
    `longitud` VARCHAR(191) NOT NULL,
    `color` VARCHAR(191) NOT NULL,
    `tipologia_agua` VARCHAR(191) NOT NULL,
    `olor` VARCHAR(191) NOT NULL,
    `subsitema_rio` VARCHAR(191) NOT NULL,
    `condicion` VARCHAR(191) NOT NULL,
    `resultado_hidromorfologico` VARCHAR(191) NOT NULL,
    `extraccion_local` VARCHAR(191) NOT NULL,
    `veg_riparia` VARCHAR(191) NOT NULL,
    `nombre` VARCHAR(191) NOT NULL,
    `lluvias_recientes` VARCHAR(191) NOT NULL,
    `nombre_del_rio` VARCHAR(191) NOT NULL,
    `corregimiento` VARCHAR(191) NOT NULL,
    `presencia_basura` VARCHAR(191) NOT NULL,
    `tipo_de_habitat` VARCHAR(191) NOT NULL,
    `canalizacion` VARCHAR(191) NOT NULL,
    `zona_de_uso` VARCHAR(191) NOT NULL,
    `ruta_imagen` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
